name: Deploy Hyperasset to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Upload vers DEV
      - name: Upload to Azure Blob Storage (DEV)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_DEV }} \
              --auth-mode login \
              --destination '$web' \
              --source ./hyperassets \
              --overwrite


#      # Upload vers UAT
#      - name: Upload assets to UAT storage
#        uses: azure/CLI@v1
#        with:
#          azcliversion: 2.53.0
#          inlineScript: |
#            echo "Uploading to UAT..."
#            az storage blob upload-batch \
#              --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING_UAT }}" \
#              -d '$web/hyperasset' \
#              -s "./hyperasset"
#
#      # Upload vers PROD
#      - name: Upload assets to PROD storage
#        uses: azure/CLI@v1
#        with:
#          azcliversion: 2.53.0
#          inlineScript: |
#            echo "Uploading to PROD..."
#            az storage blob upload-batch \
#              --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING_PROD }}" \
#              -d '$web/hyperasset' \
#              -s "./hyperasset"
