name: Deploy Hyperassets

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout du repo
      - uses: actions/checkout@v3

      # 2️⃣ Upload vers Azure Storage (DEV)
      - name: Upload hyperassets to DEV
        uses: azure/storage-blob-upload@v1
        with:
          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING_DEV }}
          container-name: '$web'
          source: ./hyperassets
          destination: hyperasset
          overwrite: true

#      # 3️⃣ Upload vers Azure Storage (UAT)
#      - name: Upload hyperassets to UAT
#        uses: azure/storage-blob-upload@v1
#        with:
#          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING_UAT }}
#          container-name: '$web'
#          source: ./hyperassets
#          destination: hyperasset
#          overwrite: true
#
#      # 4️⃣ Upload vers Azure Storage (PROD)
#      - name: Upload hyperassets to PROD
#        uses: azure/storage-blob-upload@v1
#        with:
#          connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING_PROD }}
#          container-name: '$web'
#          source: ./hyperassets
#          destination: hyperasset
#          overwrite: true
